FROM php:8.3-fpm

RUN apt-get update \
	&& apt-get install -y --no-install-recommends libxml2-dev \
	&& docker-php-ext-install dom xml xmlwriter pdo pdo_mysql \
	&& rm -rf /var/lib/apt/lists/*

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /var/www/html

COPY . .

RUN composer install
